allocatr/users/urls.py
from django.urls import path

from allocatr.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

allocatr/wallet/urls.py
from django.urls import path

from . import views

app_name = "wallet"

urlpatterns = [
    # Home
    path("", views.DashboardHome.as_view(), name="home"),
    path("current-month/", views.get_current_month, name="current_month"),
    path(
        "previous-month/<str:month>/", views.get_previous_month, name="previous_month"
    ),
    path("next-month/<str:month>/", views.get_next_month, name="next_month"),
    # Transaction Views
    path("transactions/", views.TransactionListView.as_view(), name="transactions"),
    path(
        "hx/transactions/",
        views.TransactionPartialListView.as_view(),
        name="transaction_list_partial",
    ),
    path(
        "transactions/<int:pk>/",
        views.TransactionDetailView.as_view(),
        name="transaction_detail",
    ),
    path(
        "transactions/add-income/", views.IncomeCreateView.as_view(), name="add_income"
    ),
    path(
        "transactions/<int:pk>/update-income/",
        views.IncomeUpdateView.as_view(),
        name="edit_income",
    ),
    path(
        "transactions/add-expense/",
        views.ExpenseCreateView.as_view(),
        name="add_expense",
    ),
    path(
        "transactions/<int:pk>/update-expense/",
        views.ExpenseUpdateView.as_view(),
        name="edit_expense",
    ),
    path(
        "transactions/add-transfer/",
        views.TransferCreateView.as_view(),
        name="add_transfer",
    ),
    path(
        "transactions/<int:pk>/update-transfer/",
        views.TransferUpdateView.as_view(),
        name="edit_transfer",
    ),
    path(
        "transactions/<int:pk>/delete/",
        views.TransactionDeleteView.as_view(),
        name="delete_transaction",
    ),
    # Planned Transaction Views
    path(
        "transactions/planned/",
        views.PlannedTransactionListView.as_view(),
        name="planned_transactions",
    ),
    path(
        "transactions/planned/<int:pk>/",
        views.PlannedTransactionDetailView.as_view(),
        name="planned_transaction_detail",
    ),
    path(
        "transactions/planned/expenses/add/",
        views.PlannedExpenseCreateView.as_view(),
        name="add_planned_expense",
    ),
    path(
        "transactions/planned/income/add/",
        views.PlannedIncomeCreateView.as_view(),
        name="add_planned_income",
    ),
    path(
        "transactions/planned/income/<int:pk>/update/",
        views.PlannedExpenseUpdateView.as_view(),
        name="edit_planned_income",
    ),
    path(
        "transactions/planned/expenses/<int:pk>/update/",
        views.PlannedExpenseUpdateView.as_view(),
        name="edit_planned_expense",
    ),
    path(
        "transactions/planned/<int:pk>/delete/",
        views.PlannedTransactionDeleteView.as_view(),
        name="delete_planned_transaction",
    ),
    # Account Views
    path("accounts/", views.AccountListView.as_view(), name="accounts"),
    path(
        "accounts/<int:pk>/",
        views.AccountDetailView.as_view(),
        name="account_detail",
    ),
    path(
        "accounts/partial/",
        views.AccountPartialListView.as_view(),
        name="accounts_list",
    ),
    path("accounts/add/", views.AccountCreateView.as_view(), name="add_account"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdateView.as_view(),
        name="edit_account",
    ),
    path(
        "accounts/<int:pk>/update-balance/",
        views.AccountBalanceUpdateView.as_view(),
        name="update_account_balance",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDeleteView.as_view(),
        name="delete_account",
    ),
    # Category Views
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("categories/add/", views.CategoryCreateView.as_view(), name="add_category"),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdateView.as_view(),
        name="edit_category",
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="delete_category",
    ),
    # Budget Views
    path("budgets/", views.BudgetListView.as_view(), name="budgets"),
    path("budgets/<int:pk>/", views.BudgetDetailView.as_view(), name="budget_detail"),
    path("budgets/add/", views.BudgetCreateView.as_view(), name="add_budget"),
    path(
        "budgets/category/<int:category_id>/add/",
        views.CategoryBudgetCreateView.as_view(),
        name="add_category_budget",
    ),
    path(
        "budgets/<int:pk>/update/", views.BudgetUpdateView.as_view(), name="edit_budget"
    ),
    path(
        "budgets/master-budget/",
        views.MasterBudgetPartialView.as_view(),
        name="master_budget_partial",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("allocatr.wallet.urls", namespace="wallet")),
    path(
        "home/", TemplateView.as_view(template_name="pages/home.html"), name="home"
    ),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("allocatr.users.urls", namespace="users")),
    path("user-accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

allocatr/wallet/models.py
import uuid
from datetime import date, datetime

from colorfield.fields import ColorField
from dateutil.relativedelta import relativedelta
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

from .querysets import AccountQuerySet, CategoryQuerySet, TransactionQuerySet
from .utils import COLOR_PALETTE, get_month_range, is_color_dark

User = get_user_model()


class TimeStampedUUIDModel(models.Model):
    pkid = models.BigAutoField(primary_key=True, editable=False)
    id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ["-created_at", "-updated_at"]


class Month(models.Model):
    user = models.ForeignKey(
        User, verbose_name=_("User"), related_name="months", on_delete=models.CASCADE
    )
    first_day = models.DateField()
    last_day = models.DateField(blank=True)
    month_code = models.PositiveSmallIntegerField(
        blank=True,
        editable=False,
        validators=[
            RegexValidator(
                regex=r"^\d{4}$", message="Month code must be 4 digits long"
            ),
            RegexValidator(
                regex=r"^\d{2}$",
                message="Last 2 digits of month code must be between 01 and 12",
                code="invalid_month_code",
            ),
            RegexValidator(
                regex=r"^(0[1-9]|1[0-2])$",
                message="Last 2 digits of month code must be between 01 and 12",
                code="invalid_month_code",
            ),
        ],
    )
    override_last_day = models.BooleanField(default=True)
    month_days = models.PositiveSmallIntegerField(default=30, editable=False)

    def get_or_create_next_month(self):
        next_month = (
            Month.objects.filter(user=self.user, first_day__gt=self.first_day)
            .order_by("first_day")
            .first()
        )
        if not next_month:
            next_month = Month.objects.create(
                user=self.user, first_day=self.first_day + relativedelta(months=1)
            )
        return next_month

    def get_or_create_previous_month(self):
        previous_month = (
            Month.objects.filter(user=self.user, first_day__lt=self.first_day)
            .order_by("-first_day")
            .first()
        )
        if not previous_month:
            previous_month = Month.objects.create(
                user=self.user, first_day=self.first_day - relativedelta(months=1)
            )
        return previous_month

    class Meta:
        unique_together = (("user", "month_code"),)
        ordering = ("-first_day",)

    def save(self, *args, **kwargs):
        self.month_code = datetime.strftime(self.first_day, "%y%m")
        if self.override_last_day:
            _, self.last_day = get_month_range(self.first_day.day, self.first_day)
        self.month_days = (self.last_day - self.first_day).days + 1
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.first_day.strftime('%B')} {self.first_day.year}"


class UserSettings(models.Model):
    class Currency(models.TextChoices):
        AUD = "AUD", _("Australia Dollar")
        CAD = "CAD", _("Canada Dollar")
        CNY = "RMB", _("China Yuan Renminbi")
        EUR = "EUR", _("Euro Member Countries")
        RON = "RON", _("Romania Leu")
        GBP = "GBP", _("United Kingdom Pound")
        USD = "USD", _("United States Dollar")

    user = models.OneToOneField(User, related_name="settings", on_delete=models.CASCADE)
    currency = models.CharField(
        max_length=3, choices=Currency.choices, default=Currency.USD
    )
    show_decimal_places = models.BooleanField(default=True)
    start_day_of_month = models.PositiveSmallIntegerField(
        default=1,
        validators=[
            MaxValueValidator(28, message=_("Value must be between 1 and 28.")),
            MinValueValidator(1, message=_("Value must be between 1 and 28.")),
        ],
    )

    class Meta:
        verbose_name_plural = "User Settings"

    def save(self, *args, **kwargs):
        # Check if object is being updated and if start_day_of_month has changed
        if (
            not self._state.adding
            and self.start_day_of_month
            != self.__class__.objects.get(pk=self.pk).start_day_of_month
        ):
            # If start_day_of_month has changed, update all months
            self.update_all_following_months(self.start_day_of_month)
        super().save(*args, **kwargs)

    def update_all_following_months(self, new_start_day_of_month: int):
        # Get all following months and update them
        following_months = Month.objects.filter(
            first_day__gte=date.today(), user=self.user
        )
        for month in following_months:
            month.first_day = month.first_day.replace(day=new_start_day_of_month)
            month.save()


class Account(TimeStampedUUIDModel):
    class AccountType(models.TextChoices):
        GENERAL = "GA", _("General")
        CASH = "CA", _("Cash")
        CURRENT = "CU", _("Current")
        SAVINGS = "SA", _("Savings")
        INSURANCE = "IS", _("Insurance")
        INVESTMENT = "IV", _("Investment")
        CREDIT_CARD = "CC", _("Credit Card")
        LOAN = "LO", _("Loan")

    user = models.ForeignKey(
        User, verbose_name=_("User"), related_name="accounts", on_delete=models.CASCADE
    )
    name = models.CharField(verbose_name=_("Name"), max_length=50)
    account_type = models.CharField(
        verbose_name=_("Type"),
        max_length=2,
        choices=AccountType.choices,
        default=AccountType.GENERAL,
    )
    current_balance = models.DecimalField(
        verbose_name=_("Balance"), max_digits=10, decimal_places=2, default=0.0
    )
    balance_can_be_negative = models.BooleanField(
        verbose_name=_("Balance can be negative"), default=False
    )
    active = models.BooleanField(verbose_name=_("Active"), default=True)
    exclude_from_budget = models.BooleanField(
        verbose_name=_("Exclude from budget"), default=False
    )
    show_on_dashboard = models.BooleanField(
        verbose_name=_("Show on Dashboard"), default=True
    )
    color = ColorField(
        verbose_name=_("Color on Dashboard"), samples=COLOR_PALETTE, default="#7DD181"
    )
    text_color = models.CharField(
        verbose_name=_("Text color"), max_length=12, blank=True, editable=False
    )

    objects = AccountQuerySet.as_manager()

    def get_bg_color(self):
        tailwind_color = "red-500"
        for color in COLOR_PALETTE:
            if color[0] == self.color:
                tailwind_color = color[1]
        return f"bg-{tailwind_color}"

    class Meta:
        ordering = ["-active", "-created_at"]
        unique_together = (("name", "account_type"),)

    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        self.text_color = "white" if is_color_dark(self.color) else "black"
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("wallet:account_detail", kwargs={"pk": self.pk})


class Category(TimeStampedUUIDModel):
    class Group(models.TextChoices):
        INCOME = "IN", _("Income")
        EXPENSE = "EX", _("Expense")
        TRANSFER = "TR", _("Transfer")

    user = models.ForeignKey(
        User,
        verbose_name=_("User"),
        related_name="categories",
        on_delete=models.CASCADE,
    )
    group = models.CharField(
        verbose_name=_("Category group"),
        max_length=2,
        choices=Group.choices,
        default=Group.EXPENSE,
    )
    parent = models.ForeignKey(
        "self",
        related_name="subcategories",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    root_category = models.ForeignKey(
        "self",
        related_name="all_subcategories",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    name = models.CharField(_("Name"), max_length=100)
    active = models.BooleanField(verbose_name=_("Active"), default=True)
    color = ColorField(
        verbose_name=_("Color on Dashboard"), samples=COLOR_PALETTE, default="#7DD181"
    )
    text_color = models.CharField(
        verbose_name=_("Text color"), max_length=12, blank=True, editable=False
    )

    objects = CategoryQuerySet.as_manager()

    class Meta:
        verbose_name_plural = _("Categories")
        ordering = ["group", "parent__id", "id"]

    def get_all_subcategories(self):
        """Returns a queryset of all descendent categories (subcategories)"""
        descendents = []
        subcategories = self.subcategories.all()
        for subcategory in subcategories:
            descendents.append(subcategory)
            descendents.extend(subcategory.get_all_subcategories())
        return descendents

    def __str__(self):
        return str(self.name) if not self.parent else f"⤷ {self.name}"

    def save(self, *args, **kwargs):
        self.text_color = "white" if is_color_dark(self.color) else "black"
        if (
            self._state.adding
            or self.parent != self.__class__.objects.get(pkid=self.pkid).parent
        ):
            if self.parent:
                self.root_category = self.parent.root_category
            else:
                super().save(*args, **kwargs)
                self.root_category = self
                self.save()
            for child in self.subcategories.all():
                child.save()
        super().save(*args, **kwargs)


class Transaction(TimeStampedUUIDModel):
    class TransactionType(models.TextChoices):
        INCOME = "IN", _("Income")

allocatr/templates/wallet/categories/partials/add_category.html
{% load widget_tweaks %}

<!-- Modal Header -->
<header class="flex justify-between pt-2">
  <h1 class="text-2xl font-bold text-gray-700 dark:text-gray-200">Add New Category</h1>
  <button
    class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700 focus:outline-none"
    aria-label="close" @click="closeModal">
    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
      <path
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd" fill-rule="evenodd"></path>
    </svg>
  </button>
</header>

<div class="px-1 py-6 space-y-3 max-w-xl text-gray-900 dark:text-white">


  <form class="w-full" hx-post="{% url 'wallet:add_category' %}"
    @show-message="successToast.fire({title: $event.detail.value})" @category-created="closeModal"
    x-data="{group: 'EX', categories: {{ categories }} }">
    {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}

    <div class="flex flex-wrap -mx-3 mb-6">
      <!-- Name -->
      <div class="w-1/2 xs:w-2/3 px-2">
        <label for="{{ form.name.id_for_label }}" class="input-label">{{ form.name.label }}</label>
        {% render_field form.name class="text-input" type="text" %}
        {% for error in form.name.errors %}<p class="text-red-500 text-xs italic">{{ error }}</p>{% endfor %}
      </div>

      <!-- Color -->
      <div x-data="{selectedColor: '{{ form.color.value }}'}" class="w-1/2 xs:w-1/3 px-3">
        <label for="{{ form.color.id_for_label }}" class="input-label">Color</label>
        {% render_field form.color|append_attr:"x-model:selectedColor" class+="coloris text-input" %}
        {% for error in form.color.errors %}<p class="text-red-500 text-xs italic">{{ error }}</p>{% endfor %}
      </div>
    </div>

    <div class="flex flex-wrap -mx-3 mb-6">
      <!-- Category Group -->
      <div class="w-1/2 px-2">
        <label for="{{ form.group.id_for_label }}" class="input-label">{{ form.group.label }}</label>
        {% render_field form.group class+="text-input" x-model="group" %}
        {% for error in form.group.errors %}<p class="text-red-500 text-xs italic">{{ error }}</p>{% endfor %}
      </div>
      <!-- Parent Category -->
      <div class="w-1/2 px-2">
        <label for="{{ form.parent.id_for_label }}" class="input-label">Parent Category</label>
        <select name="parent" id="id_parent" class="text-input">
          <option value selected>---------</option>
          <template x-for="category in categories" :key="category.id">
            <option :value="category.id" x-show="!group || category.group === group" x-text="category.name"></option>
          </template>
        </select>
        {% for error in form.parent.errors %}<p class="text-red-500 text-xs italic">{{ error }}</p>{% endfor %}
      </div>
    </div>

    <div class="flex flex-wrap -mx-1 mb-6">
      <!-- Status -->
      <div class="flex w-full">
        <div class="flex items-center h-5">
          {% render_field form.active class+="checkbox-input" %}
        </div>
        <div class="ml-2 text-sm">
          <label for="{{ form.active.id_for_label }}"
            class="font-medium text-gray-900 dark:text-gray-300">{{ form.active.label }}</label>
          {% for error in form.active.errors %}<p class="text-red-500 text-xs italic">{{ error }}</p>{% endfor %}
        </div>
      </div>
    </div>

    <footer class="flex items-center justify-end px-6 py-2 -mx-6 -mb-4 space-x-6 flex-row bg-white dark:bg-gray-800">
      <button @click="closeModal" class="secondaryBtn">Cancel</button>
      <button type="submit" class="primaryBtn">Add</button>
    </footer>

  </form>

</div>

<script>
  Coloris({
    el: '.coloris'
  });
  Coloris.setInstance('#id_color', {
    themeMode: 'auto',
    alpha: false,
    theme: 'polaroid',
    format: 'hex',
    onChange: (color) => {
      document.getElementById('id_color').style.backgroundColor = color;
      document.getElementById('id_color').style.borderColor = color;
    }
  })

</script>

<style>
  .clr-field button {
    border-top-right-radius: 4px;
    border-bottom-right-radius: 4px;
  }

</style>

allocatr/templates/wallet/categories/partials/detail.html
<!-- Modal Header -->
<header class="flex justify-between mt-2 rounded-lg pl-6 pr-8 py-3 scale-110 -translate-y-5"
  style="background-color: {{ category.color }}; color: {{ category.text_color }}">
  <h1 class="mt-1 text-2xl font-semibold text-gray-700 dark:text-gray-200" style="color: {{ category.text_color }}">
    <span class="px-3 py-1 rounded-lg">
      {% if category.group == "EX" %}
      <svg class="inline-block w-8 h-8 p-1 rounded-full"
        style="background-color: {{ category.text_color }}; color: {{ category.color }}" fill="none"
        stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5">
        </path>
      </svg>
      {% elif category.group == "IN"%}
      <svg class="inline-block w-8 h-8 p-1 rounded-full"
        style="background-color: {{ category.text_color }}; color: {{ category.color }}" fill="none"
        stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3">
        </path>
      </svg>
      {% elif category.group == "TR"%}
      <svg class="inline-block w-8 h-8 p-1 rounded-full"
        style="background-color: {{ category.text_color }}; color: {{ category.color }}" fill="none"
        stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
        aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round"
          d="M7.5 21L3 16.5m0 0L7.5 12M3 16.5h13.5m0-13.5L21 7.5m0 0L16.5 12M21 7.5H7.5"></path>
      </svg>
      {% endif %}
    </span>
    {{ category.name }}
  </h1>
  <button
    class="inline-flex items-center justify-center w-6 h-6 mt-2 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700 focus:outline-none"
    aria-label="close" @click="closeStickyModal" style="color: {{ category.text_color }}">
    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
      <path
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd" fill-rule="evenodd"></path>
    </svg>
  </button>
</header>

<!-- Modal body -->
<div class="flex px-1 mb-4 max-w-xl text-gray-900 dark:text-white" id="modal-body">

  <div class="relative overflow-x-auto w-full">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-900 uppercase dark:text-gray-400">
        <tr>
          <th scope="col" class="px-1 md:px-3 py-1">
            Transaction
          </th>
          <th scope="col" class="px-1 md:px-3 py-1">
            Amount
          </th>
          <th scope="col" class="px-1 md:px-3 py-1">
            Account
          </th>
          <th scope="col" class="px-1 md:px-3 py-1">
            Date
          </th>
        </tr>
      </thead>
      <tbody>
        {% for tr in transactions %}
        <tr hx-get="{% url 'wallet:transaction_detail' tr.pk %}" hx-target="#modal" hx-trigger="click"
          @click="openModal"
          class="bg-white dark:bg-gray-800 border-b dark:border-gray-700 cursor-pointer dark:hover:bg-gray-600">
          <th scope="row" class="px-1 md:px-3 py-2 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            {{ tr.title|capfirst }}
          </th>
          <td class="px-1 md:px-3 py-2">
            {{ user_settings.currency }} {{ tr.amount|floatformat:0 }}
          </td>
          <td class="px-1 md:px-3 py-2">
            {{ tr.account }}
          </td>
          <td class="px-1 md:px-3 py-2">
            {{ tr.date|date:"d M" }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


</div>

<div class="flex flex-row justify-between px-4 mb-4">
  <div class="w-1/2 max-w-[130px]">
    <canvas id="transactions-chart"></canvas>
  </div>
  <div class="w-1/2">
    <p class="text-gray-800 dark:text-white text-2xl font-bold">{{ user_settings.currency }}
      {{ amount_total.amount__sum|floatformat:0 }}</p>
  </div>
</div>


<!-- Modal Footer -->
<footer class="flex items-center justify-end px-6 pt-2 pb-4 -mx-2 -mb-1 space-x-6 flex-row bg-white dark:bg-gray-800">
  <button
    class="secondaryBtn"
    hx-get="{% url 'wallet:add_category_budget' category_id=category.pk %}"
    hx-trigger="click" hx-target="#modal" @click="openModal"
    >
    Create budget
  </button>
  <button hx-post="{% url 'wallet:delete_category' category.pk %}" hx-trigger="isConfirmed"
    @click="twSwal.fire({title: 'Are you sure?', text:'This category will be deleted! You will not be able to revert this!', icon: 'warning', showConfirmButton: true, showCancelButton: true, confirmButtonText: 'Yes, delete it!'}).then(result => {if (result.isConfirmed) {$dispatch('isConfirmed')}})"
    @show-message="successToast.fire({title: $event.detail.value})" class="redBtn">
    Delete
  </button>

  <button hx-get="{% url 'wallet:edit_category' category.pk %}" hx-trigger="click" hx-target="#modal" @click="openModal"
    class="primaryBtn">
    Edit category
  </button>

</footer>

<script>
  new Chart(
    document.getElementById('transactions-chart').getContext('2d'), {
      type: 'doughnut',
      data: {
        labels: {{ transaction_names | safe }},
        datasets: [{
          data: {{ amounts | safe }},
        }],
      },
      options: {
        plugins: {
          legend: {
            display: false
          }
        }
      }
    }
  );

</script>