allocatr/users/urls.py
from django.urls import path

from allocatr.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

allocatr/wallet/urls.py
from django.urls import path

from . import views

app_name = "wallet"

urlpatterns = [
    # Home
    path("", views.DashboardHome.as_view(), name="home"),
    path("current-month/", views.get_current_month, name="current_month"),
    path(
        "previous-month/<str:month>/", views.get_previous_month, name="previous_month"
    ),
    path("next-month/<str:month>/", views.get_next_month, name="next_month"),
    # Transaction Views
    path("transactions/", views.TransactionListView.as_view(), name="transactions"),
    path(
        "hx/transactions/",
        views.TransactionPartialListView.as_view(),
        name="transaction_list_partial",
    ),
    path(
        "transactions/<int:pk>/",
        views.TransactionDetailView.as_view(),
        name="transaction_detail",
    ),
    path(
        "transactions/add-income/", views.IncomeCreateView.as_view(), name="add_income"
    ),
    path(
        "transactions/<int:pk>/update-income/",
        views.IncomeUpdateView.as_view(),
        name="edit_income",
    ),
    path(
        "transactions/add-expense/",
        views.ExpenseCreateView.as_view(),
        name="add_expense",
    ),
    path(
        "transactions/<int:pk>/update-expense/",
        views.ExpenseUpdateView.as_view(),
        name="edit_expense",
    ),
    path(
        "transactions/add-transfer/",
        views.TransferCreateView.as_view(),
        name="add_transfer",
    ),
    path(
        "transactions/<int:pk>/update-transfer/",
        views.TransferUpdateView.as_view(),
        name="edit_transfer",
    ),
    path(
        "transactions/<int:pk>/delete/",
        views.TransactionDeleteView.as_view(),
        name="delete_transaction",
    ),
    # Planned Transaction Views
    path(
        "transactions/planned/",
        views.PlannedTransactionListView.as_view(),
        name="planned_transactions",
    ),
    path(
        "transactions/planned/<int:pk>/",
        views.PlannedTransactionDetailView.as_view(),
        name="planned_transaction_detail",
    ),
    path(
        "transactions/planned/expenses/add/",
        views.PlannedExpenseCreateView.as_view(),
        name="add_planned_expense",
    ),
    path(
        "transactions/planned/income/add/",
        views.PlannedIncomeCreateView.as_view(),
        name="add_planned_income",
    ),
    path(
        "transactions/planned/income/<int:pk>/update/",
        views.PlannedExpenseUpdateView.as_view(),
        name="edit_planned_income",
    ),
    path(
        "transactions/planned/expenses/<int:pk>/update/",
        views.PlannedExpenseUpdateView.as_view(),
        name="edit_planned_expense",
    ),
    path(
        "transactions/planned/<int:pk>/delete/",
        views.PlannedTransactionDeleteView.as_view(),
        name="delete_planned_transaction",
    ),
    # Account Views
    path("accounts/", views.AccountListView.as_view(), name="accounts"),
    path(
        "accounts/<int:pk>/",
        views.AccountDetailView.as_view(),
        name="account_detail",
    ),
    path(
        "accounts/partial/",
        views.AccountPartialListView.as_view(),
        name="accounts_list",
    ),
    path("accounts/add/", views.AccountCreateView.as_view(), name="add_account"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdateView.as_view(),
        name="edit_account",
    ),
    path(
        "accounts/<int:pk>/update-balance/",
        views.AccountBalanceUpdateView.as_view(),
        name="update_account_balance",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDeleteView.as_view(),
        name="delete_account",
    ),
    # Category Views
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category_detail",
    ),
    path("categories/add/", views.CategoryCreateView.as_view(), name="add_category"),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdateView.as_view(),
        name="edit_category",
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="delete_category",
    ),
    # Budget Views
    path("budgets/", views.BudgetListView.as_view(), name="budgets"),
    path("budgets/<int:pk>/", views.BudgetDetailView.as_view(), name="budget_detail"),
    path("budgets/add/", views.BudgetCreateView.as_view(), name="add_budget"),
    path(
        "budgets/category/<int:category_id>/add/",
        views.CategoryBudgetCreateView.as_view(),
        name="add_category_budget",
    ),
    path(
        "budgets/<int:pk>/update/", views.BudgetUpdateView.as_view(), name="edit_budget"
    ),
    path(
        "budgets/master-budget/",
        views.MasterBudgetPartialView.as_view(),
        name="master_budget_partial",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("allocatr.wallet.urls", namespace="wallet")),
    path(
        "home/", TemplateView.as_view(template_name="pages/home.html"), name="home"
    ),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("allocatr.users.urls", namespace="users")),
    path("user-accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

allocatr/users/views.py
from allauth.account.views import LogoutView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "profile_photo"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserLogoutView(LogoutView):
    template_name = "users"

allocatr/wallet/views/account.py
import json
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse

from ..forms import AccountBalanceForm, AccountForm
from ..htmx_views import (
    HtmxDetailView,
    HtmxListView,
    HtmxOnlyCreateView,
    HtmxOnlyDeleteView,
    HtmxOnlyListView,
    HtmxOnlyUpdateView,
)
from ..models import Account, Transaction, UserSettings
from ..services import get_or_create_month


class AccountPartialListView(LoginRequiredMixin, HtmxOnlyListView):
    model = Account
    context_object_name = "accounts"
    template_name = "wallet/accounts/partials/account_cards.html"

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        return qs.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_accounts = Account.objects.filter(user=self.request.user)
        user_settings = UserSettings.objects.get(user=self.request.user)
        wallet_balance = sum([account.current_balance for account in user_accounts])
        context["currency"] = user_settings.currency
        context["wallet_balance"] = wallet_balance
        return context


class AccountListView(LoginRequiredMixin, HtmxListView):
    model = Account
    htmx_template_name = "wallet/accounts/partials/list.html"
    template_name = "wallet/accounts/account_list.html"

    def get_queryset(self, **kwargs):
        qs = super().get_queryset(**kwargs)
        return qs.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_settings = UserSettings.objects.get(user=self.request.user)
        day_or_month = self.request.GET.get("month", date.today())
        month = get_or_create_month(self.request.user, day_or_month)
        accounts = []
        for account in context["account_list"]:
            transactions = Transaction.objects.filter(
                Q(account=account) | Q(to_account=account),
                date__gte=month.first_day,
                date__lte=month.last_day,
            )
            accounts.append({"details": account, "transactions": transactions})
        context["accounts"] = accounts
        context["user_settings"] = user_settings
        return context


class AccountDetailView(LoginRequiredMixin, HtmxDetailView):
    model = Account
    context_object_name = "account"
    htmx_template_name = "wallet/accounts/partials/detail.html"
    template_name = "wallet/accounts/account_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_settings = UserSettings.objects.get(user=self.request.user)
        day_or_month = self.request.GET.get("month", date.today())
        month = get_or_create_month(self.request.user, day_or_month)
        filtered_transactions = Transaction.objects.filter(
            Q(account=self.get_object()) | Q(to_account=self.get_object()),
            date__gte=month.first_day,
            date__lte=month.last_day,
        )
        context["transactions"] = filtered_transactions
        income_amounts = []
        expenses_amounts = []
        income = []
        expenses = []
        income_colors = []
        expense_colors = []
        for tr in filtered_transactions.order_by("-created_at"):
            if tr.transaction_type == Transaction.TransactionType.EXPENSE or (
                tr.transaction_type == Transaction.TransactionType.TRANSFER
                and tr.account == context["account"]
            ):
                expenses_amounts.append(int(tr.amount))
                expenses.append(tr.title)
                expense_colors.append(tr.category.color)
            elif tr.transaction_type == Transaction.TransactionType.INCOME:
                income_amounts.append(int(tr.amount))
                income.append(tr.title)
                income_colors.append(tr.category.color)
        context["expenses"] = expenses
        context["expenses_amounts"] = expenses_amounts
        context["expense_colors"] = expense_colors
        context["expense_total"] = sum(expenses_amounts)
        context["income"] = income
        context["income_amounts"] = income_amounts
        context["income_colors"] = income_colors
        context["income_total"] = sum(income_amounts)
        context["user_settings"] = user_settings
        return context


class AccountCreateView(LoginRequiredMixin, HtmxOnlyCreateView):
    model = Account
    form_class = AccountForm
    template_name = "wallet/accounts/partials/add_account.html"

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        headers = {
            "HX-Trigger": json.dumps(
                {
                    "account-created": None,
                    "accounts-changed": None,
                    "show-message": f"Account {form.instance.name} created",
                }
            )
        }
        return HttpResponse(status=204, headers=headers)


class AccountUpdateView(LoginRequiredMixin, HtmxOnlyUpdateView):
    model = Account
    form_class = AccountForm
    context_object_name = "account"
    template_name = "wallet/accounts/partials/update_account.html"

    def form_valid(self, form):
        self.object = form.save()  # noqa
        headers = {
            "HX-Trigger": json.dumps(
                {
                    "account-edited": None,
                    "accounts-changed": None,
                    "show-message": f"Account {form.instance.name} updated",
                }
            )
        }
        return HttpResponse(status=204, headers=headers)


class AccountBalanceUpdateView(LoginRequiredMixin, HtmxOnlyUpdateView):
    model = Account
    form_class = AccountBalanceForm
    context_object_name = "account"
    template_name = "wallet/accounts/partials/update_account_balance.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.get_object()
        return kwargs

    def form_valid(self, form):
        old_balance = form.initial["current_balance"]
        new_balance = form.cleaned_data["current_balance"]
        Transaction.objects.create(
            transaction_type="AD",
            amount=old_balance - new_balance,
            title=f"Balance adjustment for {form.instance.name}",
            account=form.instance,
        )
        self.object = form.save()  # noqa
        headers = {
            "HX-Trigger": json.dumps(
                {
                    "account-edited": None,
                    "accounts-changed": None,
                    "show-message": f"Account {form.instance.name} balance adjusted",
                }
            )
        }
        return HttpResponse(status=204, headers=headers)


class AccountDeleteView(LoginRequiredMixin, HtmxOnlyDeleteView):
    model = Account

    def form_valid(self, form):
        name = self.object.name
        self.object.delete()
        headers = {
            "HX-Trigger": json.dumps(
                {
                    "account-deleted": None,
                    "accounts-changed": None,
                    "show-message": f"Account {name} deleted",
                }
            )
        }
        return HttpResponse(status=204, headers=headers)

allocatr/wallet/views/dashboard.py
from datetime import date

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import TemplateView

from ..models import UserSettings
from ..services import get_or_create_month

User = get_user_model()


class DashboardHome(LoginRequiredMixin, TemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_settings = UserSettings.objects.get(user=self.request.user)
        context["user_settings"] = user_settings
        return context

    def get_template_names(self):
        if self.request.headers.get("HX-Request"):
            return "wallet/home/partials/home.html"
        return "wallet/home/dashboard_home.html"


def get_current_month(request):
    current_month = get_or_create_month(request.user, date.today())
    response = {
        "firstDay": current_month.first_day.isoformat(),
        "lastDay": current_month.last_day.isoformat(),
        "month": current_month.month_code,
    }
    return JsonResponse(response, safe=False)


def get_previous_month(request, month: str):
    previous_month = get_or_create_month(request.user, month, -15)
    response = {
        "firstDay": previous_month.first_day.isoformat(),
        "lastDay": previous_month.last_day.isoformat(),
        "month": previous_month.month_code,
    }
    return JsonResponse(response, safe=False)


def get_next_month(request, month: str):
    next_month = get_or_create_month(request.user, month, 45)
    response = {
        "firstDay": next_month.first_day.isoformat(),
        "lastDay": next_month.last_day.isoformat(),
        "month": next_month.month_code,
    }
    return JsonResponse(response, safe=False)

allocatr/templates/wallet/transactions/partials/detail.html
<!-- Modal Header -->
<header class="flex justify-between mt-2">
  <h1 class="text-2xl font-thin text-gray-700 dark:text-gray-200">{{ transaction.title }}</h1>
  <button
    class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700 focus:outline-none"
    aria-label="close" @click="closeModal">
    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
      <path
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd" fill-rule="evenodd"></path>
    </svg>
  </button>
</header>

<!-- Modal body -->
<div class="px-1 py-6 space-y-4 max-w-xl text-gray-900 dark:text-white">
  <dl class="grid grid-cols-6 gap-6">

    <div class="col-span-6 sm:col-span-3">
      {% if transaction.get_transaction_type_display == 'Income' %}
      <dd class="text-xl font-semibold text-green-600">
        <i class="bi bi-arrow-up-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>

      {% elif transaction.get_transaction_type_display == 'Expense' %}
      <dd class="text-xl font-semibold text-red-600">
        <i class="bi bi-arrow-down-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>

      {% elif transaction.get_transaction_type_display == 'Transfer' %}
      <dd class="text-xl font-semibold text-blue-500">
        <i class="bi bi-arrow-left-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>
      {% endif %}
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dd class="text-lg font-semibold">{{ transaction.date|date:"d M Y" }}</dd>
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Account</dt>
      <dd class="text-lg font-semibold">
        <span class="px-2 py-1 font-semibold leading-tight rounded-lg"
          style="background-color: {{ transaction.account.color }}; color: {{ transaction.account.text_color }}">
          {{ transaction.account }}
        </span>
      </dd>
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Category</dt>
      <dd class="text-lg font-semibold">
        <span class="px-2 py-1 rounded-lg"
          style="background-color: {{ transaction.category.color }}; color: {{ transaction.category.text_color }}; opacity: 0.8;">
          {{ transaction.category }}
        </span>
      </dd>
    </div>

  </dl>
</div>


<!-- Modal Footer -->
<footer class="flex items-center justify-end px-6 pt-2 pb-4 -mx-6 -mb-2 space-x-6 flex-row bg-white dark:bg-gray-800">
  <button hx-post="{% url 'wallet:delete_transaction' transaction.pk %}" hx-trigger="isConfirmed"
    @click="twSwal.fire({title: 'Are you sure?', text:'This transaction will be deleted! You will not be able to revert this!', icon: 'warning', showConfirmButton: true, showCancelButton: true, confirmButtonText: 'Yes, delete it!'}).then(result => {if (result.isConfirmed) {$dispatch('isConfirmed')}})"
    @show-message="successToast.fire({title: $event.detail.value})" class="redBtn">
    Delete
  </button>

  {% if transaction.get_transaction_type_display == 'Income' %}
  <button hx-get="{% url 'wallet:edit_income' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit income
  </button>

  {% elif transaction.get_transaction_type_display == 'Expense' %}
  <button hx-get="{% url 'wallet:edit_expense' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit expense
  </button>
  {% elif transaction.get_transaction_type_display == 'Transfer' %}
  <button hx-get="{% url 'wallet:edit_transfer' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit transfer
  </button>
  {% endif %}

</footer>

allocatr/templates/wallet/transactions/partials/transaction_detail.html
<!-- Modal Header -->
<header class="flex justify-between mt-2">
  <h1 class="text-2xl font-thin text-gray-700 dark:text-gray-200">{{ transaction.title }}</h1>
  <button
    class="inline-flex items-center justify-center w-6 h-6 text-gray-400 transition-colors duration-150 rounded dark:hover:text-gray-200 hover: hover:text-gray-700 focus:outline-none"
    aria-label="close" @click="closeModal">
    <svg class="w-4 h-4" fill="currentColor" viewBox="0 0 20 20" role="img" aria-hidden="true">
      <path
        d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
        clip-rule="evenodd" fill-rule="evenodd"></path>
    </svg>
  </button>
</header>

<!-- Modal body -->
<div class="px-1 py-6 space-y-4 max-w-xl text-gray-900 dark:text-white">
  <dl class="grid grid-cols-6 gap-6">

    <div class="col-span-6 sm:col-span-3">
      {% if transaction.get_transaction_type_display == 'Income' %}
      <dd class="text-xl font-semibold text-green-600">
        <i class="bi bi-arrow-up-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>

      {% elif transaction.get_transaction_type_display == 'Expense' %}
      <dd class="text-xl font-semibold text-red-600">
        <i class="bi bi-arrow-down-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>

      {% elif transaction.get_transaction_type_display == 'Transfer' %}
      <dd class="text-xl font-semibold text-blue-500">
        <i class="bi bi-arrow-left-right"></i> lei {{ transaction.amount|floatformat:0 }}
      </dd>
      {% endif %}
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dd class="text-lg font-semibold">{{ transaction.date|date:"d M Y" }}</dd>
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Account</dt>
      <dd class="text-lg font-semibold">
        <span class="px-2 py-1 font-semibold leading-tight rounded-lg"
          style="background-color: {{ transaction.account.color }}; color: {{ transaction.account.text_color }}">
          {{ transaction.account }}
        </span>
      </dd>
    </div>

    <div class="col-span-6 sm:col-span-3">
      <dt class="mb-1 text-gray-500 md:text-lg dark:text-gray-400">Category</dt>
      <dd class="text-lg font-semibold">
        <span class="px-2 py-1 rounded-lg"
          style="background-color: {{ transaction.category.color }}; color: {{ transaction.category.text_color }}; opacity: 0.8;">
          {{ transaction.category }}
        </span>
      </dd>
    </div>

  </dl>
</div>


<!-- Modal Footer -->
<footer class="flex items-center justify-end px-6 pt-2 pb-4 -mx-6 -mb-2 space-x-6 flex-row bg-white dark:bg-gray-800">
  <button hx-post="{% url 'wallet:delete_transaction' transaction.pk %}" hx-trigger="isConfirmed"
    @click="twSwal.fire({title: 'Are you sure?', text:'This transaction will be deleted! You will not be able to revert this!', icon: 'warning', showConfirmButton: true, showCancelButton: true, confirmButtonText: 'Yes, delete it!'}).then(result => {if (result.isConfirmed) {$dispatch('isConfirmed')}})"
    @show-message="successToast.fire({title: $event.detail.value})" class="redBtn">
    Delete
  </button>

  {% if transaction.get_transaction_type_display == 'Income' %}
  <button hx-get="{% url 'wallet:edit_income' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit income
  </button>

  {% elif transaction.get_transaction_type_display == 'Expense' %}
  <button hx-get="{% url 'wallet:edit_expense' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit expense
  </button>
  {% elif transaction.get_transaction_type_display == 'Transfer' %}
  <button hx-get="{% url 'wallet:edit_transfer' pk=transaction.pk %}" hx-trigger="click" hx-target="#modal"
    class="primaryBtn">
    Edit transfer
  </button>
  {% endif %}

</footer>